#!/bin/bash

echo "EMR Training System - GitHub Setup"
echo "=================================="
echo ""
echo "Current git status:"
git log --oneline -5
echo ""
echo "To push to GitHub:"
echo ""
echo "1. Create a new repository on GitHub (https://github.com/new)"
echo "   - Name: emr-training"
echo "   - Description: Training EMR system for AWS deployment"
echo "   - Keep it public or private as needed"
echo "   - Don't initialize with README (we already have one)"
echo ""
echo "2. Add your GitHub repository as remote:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/emr-training.git"
echo ""
echo "3. Push the code:"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "Note: Due to OneDrive sync issues, not all files have been added."
echo "You can manually add remaining files after resolving sync issues."