/**
 * Starter CQL templates for the CDS Studio editor.
 *
 * Each template is a small, self-contained CQL library that compiles cleanly
 * against the deployed HAPI's CR module (no FHIRHelpers stdlib gaps and no
 * ValueSet references that aren't loaded by `scripts/load_terminology.py`).
 *
 * Students pick one as a starting point and edit. The editor's "Insert
 * template" action replaces the current buffer.
 *
 * NB: every template defines the required `Applicability` boolean and an
 * optional `CardSummary` / `CardDetail` to demonstrate the dynamicValue path.
 */

export const CQL_STARTER_TEMPLATES = [
  {
    id: 'simple-applicability',
    label: 'Simple applicability',
    description: 'Always-fires card. Useful as a "hello world" first step.',
    cql: `library SimpleHello version '0.1.0'

using FHIR version '4.0.1'

context Patient

// Card always materializes when a patient is in context.
define Applicability:
  exists [Patient]

define CardSummary: 'Hello from a CQL service'
define CardDetail:  'This card is generated by a Library + PlanDefinition. Edit the CQL to change the rule.'
`,
  },

  {
    id: 'age-and-gender',
    label: 'Age + gender check',
    description: 'Fires for female patients aged 50–74 (textbook screening eligibility shape).',
    cql: `library AgeGenderEligibility version '0.1.0'

using FHIR version '4.0.1'

include FHIRHelpers version '4.0.1' called FHIRHelpers

context Patient

// Convert FHIR.date → CQL Date implicitly via FHIRHelpers.
define PatientAge:
  CalculateAgeInYears(Patient.birthDate)

define IsFemale:
  Coalesce(Patient.gender, 'unknown') = 'female'

define IsScreeningAge:
  PatientAge between 50 and 74

define Applicability:
  IsFemale and IsScreeningAge

define CardSummary:
  'Patient is in screening age range'

define CardDetail:
  'Patient is ' + ToString(PatientAge) + ' years old. Consider age-appropriate screening.'
`,
  },

  {
    id: 'has-condition-from-valueset',
    label: 'Active condition from a ValueSet',
    description: 'Fires when the patient has an active condition coded in your custom ValueSet.',
    cql: `library DiabetesAlert version '0.1.0'

using FHIR version '4.0.1'

include FHIRHelpers version '4.0.1' called FHIRHelpers

// Compose this ValueSet first via the "Compose ValueSet" button in the editor,
// then paste its canonical URL here. The UI inserts the line for you.
valueset "Diabetes Conditions": 'http://wintehr.example.org/ValueSet/diabetes-conditions-PASTE-YOUR-ID'

context Patient

define ActiveDiabetes:
  [Condition: "Diabetes Conditions"] C
    where C.clinicalStatus ~ 'active'

define Applicability:
  exists ActiveDiabetes

define CardSummary:
  'Patient has active diabetes — review care plan'

define CardDetail:
  'Active diabetes diagnoses present. Consider HbA1c review, statin therapy, and diabetic eye/foot exam status.'
`,
  },

  {
    id: 'days-since-last-screening',
    label: 'Days since last screening',
    description: 'Fires when no screening Observation has been recorded for 12+ months.',
    cql: `library OverdueScreening version '0.1.0'

using FHIR version '4.0.1'

include FHIRHelpers version '4.0.1' called FHIRHelpers

valueset "Screening Procedures": 'http://wintehr.example.org/ValueSet/screening-procedures-PASTE-YOUR-ID'

context Patient

define LatestScreening:
  Last(
    [Observation: "Screening Procedures"] O
      sort by effective.value
  )

define Applicability:
  LatestScreening is null
    or duration in months between FHIRHelpers.ToDateTime(LatestScreening.effective) and Now() > 12

define CardSummary:
  'Patient is overdue for screening'
`,
  },

  {
    id: 'recent-lab-value',
    label: 'Lab value above threshold',
    description: 'Fires when the most recent matching lab is above a threshold.',
    cql: `library AbnormalLab version '0.1.0'

using FHIR version '4.0.1'

include FHIRHelpers version '4.0.1' called FHIRHelpers

// Replace the LOINC code below with the test you care about (e.g. 4548-4 for HbA1c).
define MostRecentA1C:
  Last(
    [Observation: code in {Code '4548-4' from "http://loinc.org" display 'HbA1c'}] O
      sort by effective.value
  )

define A1CValue:
  FHIRHelpers.ToQuantity(MostRecentA1C.value).value

define Applicability:
  A1CValue is not null and A1CValue > 9.0

define CardSummary:
  'A1C above target'

define CardDetail:
  'Most recent HbA1c is ' + ToString(A1CValue) + '. Consider therapy intensification.'
`,
  },
];

/** Get a template by id, or null. */
export function getTemplate(id) {
  return CQL_STARTER_TEMPLATES.find((t) => t.id === id) || null;
}
