"""Add enabled column to hook_configurations

Revision ID: 292e46b20d90
Revises: 001
Create Date: 2025-08-07 17:53:43.596957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292e46b20d90'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###