#!/usr/bin/env python3
"""
Compose external WintEHR modules into the build tree (module platform
Phase 3, docs/MODULES.md).

    python3 scripts/sync-modules.py                 # apply wintehr.modules.json
    python3 scripts/sync-modules.py --reset         # remove externals, restore defaults
    python3 scripts/sync-modules.py --config X.json --root /path  # (tests)

wintehr.modules.json lists the deployment's module composition:

    { "modules": [
        { "key": "flowsheets", "source": "builtin" },
        { "key": "oncology",   "source": "git+https://github.com/x/mod@v1" },
        { "key": "referrals",  "source": "./local-modules/referrals" }
    ]}

"builtin" entries are verified to exist and otherwise untouched. External
sources must be repos/directories with the standalone layout
(scripts/new-module.py --standalone):

    module.json     { key, backendTarget?, routers: [...] }
    frontend/       vendored to frontend/src/modules/<key>/
    backend/        vendored to backend/<backendTarget or api/<key>>/

Vendoring regenerates the two GENERATED registries —
frontend/src/modules/registry.generated.js and
backend/api/routers/modules_generated.py — which the loaders consume.
The reviewable artifact is wintehr.modules.json itself; the generated
files derive from it deterministically. Vendored trees are working-tree
content: commit them in a deployment fork for permanent composition, or
run this pre-build for ephemeral composition.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

KEY_RE = re.compile(r"^[a-z][a-z0-9-]*$")

FRONTEND_REGISTRY = "frontend/src/modules/registry.generated.js"
BACKEND_REGISTRY = "backend/api/routers/modules_generated.py"

FRONTEND_HEADER = '''/**
 * GENERATED by scripts/sync-modules.py — do not hand-edit.
 * External module composition comes from wintehr.modules.json.
 */

'''

BACKEND_HEADER = '''"""GENERATED by scripts/sync-modules.py — do not hand-edit.

External module composition comes from wintehr.modules.json.
"""

'''

FRONTEND_DEFAULT = FRONTEND_HEADER + "export const EXTERNAL_MODULES = [];\n"
BACKEND_DEFAULT = BACKEND_HEADER + "EXTERNAL_MODULE_ROUTERS: dict = {}\n"


def fail(msg: str) -> None:
    sys.exit(f"sync-modules: ERROR: {msg}")


def fetch_source(source: str, workdir: Path) -> Path:
    """Materialize an external source into a local directory."""
    if source.startswith("git+"):
        url = source[len("git+"):]
        ref = None
        if "@" in url.rsplit("/", 1)[-1]:
            url, ref = url.rsplit("@", 1)
        dest = workdir / "checkout"
        cmd = ["git", "clone", "--depth", "1"]
        if ref:
            cmd += ["--branch", ref]
        cmd += [url, str(dest)]
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        return dest
    path = Path(source).expanduser().resolve()
    if not path.is_dir():
        fail(f"source path does not exist: {source}")
    return path


def load_module_json(src: Path, key: str) -> dict:
    mj = src / "module.json"
    if not mj.is_file():
        fail(f"{key}: {src} has no module.json (not a standalone module — "
             f"see scripts/new-module.py --standalone)")
    meta = json.loads(mj.read_text())
    if meta.get("key") != key:
        fail(f"{key}: module.json declares key {meta.get('key')!r} — the "
             f"composition entry and the module must agree")
    return meta


def vendor(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def sync(root: Path, config_path: Path, reset: bool) -> None:
    fe_registry = root / FRONTEND_REGISTRY
    be_registry = root / BACKEND_REGISTRY

    if reset:
        fe_registry.write_text(FRONTEND_DEFAULT)
        be_registry.write_text(BACKEND_DEFAULT)
        print("sync-modules: registries reset to empty defaults "
              "(vendored directories are left for manual removal — they may "
              "contain local changes)")
        return

    if not config_path.is_file():
        fail(f"no {config_path.name} found (nothing to compose); "
             f"use --reset to restore defaults")
    config = json.loads(config_path.read_text())
    entries = config.get("modules") or []

    external_fe: list[str] = []   # keys with a frontend manifest
    external_be: dict[str, list] = {}

    for entry in entries:
        key, source = entry.get("key"), entry.get("source")
        if not key or not KEY_RE.fullmatch(key):
            fail(f"invalid module key: {key!r}")
        if source == "builtin":
            fe_dir = root / "frontend/src/modules" / key
            be_hits = list((root / "backend/api").rglob(f"{key.replace('-', '_')}"))
            if not fe_dir.is_dir() and not be_hits:
                fail(f"builtin module '{key}' not found in the tree")
            print(f"  builtin  {key} (verified)")
            continue

        with tempfile.TemporaryDirectory() as tmp:
            src = fetch_source(source, Path(tmp))
            meta = load_module_json(src, key)

            fe_src = src / "frontend"
            if fe_src.is_dir():
                if not (fe_src / "index.js").is_file():
                    fail(f"{key}: frontend/ has no index.js manifest")
                vendor(fe_src, root / "frontend/src/modules" / key)
                external_fe.append(key)

            be_src = src / "backend"
            if be_src.is_dir():
                target = meta.get("backendTarget") or f"api/{key.replace('-', '_')}"
                if ".." in target or target.startswith("/"):
                    fail(f"{key}: illegal backendTarget {target!r}")
                routers = meta.get("routers") or []
                if not routers:
                    fail(f"{key}: backend/ present but module.json declares no routers")
                vendor(be_src, root / "backend" / target)
                pkg = target.replace("/", ".")
                external_be[key] = [
                    (r["name"], f"{pkg}.{r.get('module', 'router')}",
                     r.get("attr", "router"), {"tags": r.get("tags", [meta.get("label", key)])})
                    for r in routers
                ]
            print(f"  external {key} <- {source}")

    # Regenerate the two registries
    fe_lines = [FRONTEND_HEADER]
    for key in external_fe:
        fe_lines.append(f"import {key.replace('-', '_')} from './{key}';\n")
    fe_lines.append("\nexport const EXTERNAL_MODULES = [\n")
    for key in external_fe:
        fe_lines.append(f"  {key.replace('-', '_')},\n")
    fe_lines.append("];\n")
    fe_registry.write_text("".join(fe_lines))

    be_lines = [BACKEND_HEADER, "EXTERNAL_MODULE_ROUTERS: dict = {\n"]
    for key, routers in external_be.items():
        be_lines.append(f"    {key!r}: [\n")
        for name, module, attr, kwargs in routers:
            be_lines.append(f"        ({name!r}, {module!r}, {attr!r}, {kwargs!r}),\n")
        be_lines.append("    ],\n")
    be_lines.append("}\n")
    be_registry.write_text("".join(be_lines))

    print(f"sync-modules: composed {len(external_fe)} frontend / "
          f"{len(external_be)} backend external module(s); registries regenerated")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=None)
    parser.add_argument("--root", default=None)
    parser.add_argument("--reset", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve() if args.root else Path(__file__).resolve().parent.parent
    config = Path(args.config).resolve() if args.config else root / "wintehr.modules.json"
    sync(root, config, args.reset)


if __name__ == "__main__":
    main()
